notes_dir: zettelkasten
encrypted_dir: personal
git_dir:  /home/msytnyk/dev/github.com/notes
gpg_public_key: /home/msytnyk/.gnupg/public.gpg
gpg_private_key: /home/msytnyk/.gnupg/private.gpg
ssh_private_key: /home/msytnyk/.ssh/id_rsa
